### ISSUE TITLE
does not work for Django 1.2

### ISSUE THREAD

**Issue by vanschelven** [johnsensible/django-publish#1]
trying to use the project in django 1.2. gives me the following error:
cannot import name get_change_view_url

publish/actions.py in <module>
4. from django.contrib.admin.util import get_change_view_url, model_ngettext ...

after a little bit of digging I found that
get_change_view_url was removed in svn revision 12598
http://code.djangoproject.com/changeset?old_path=django/trunk/django/contrib/admin/util.py&old=12598&new_path=django/trunk/django/contrib/admin/util.py&new=12598

**Comment by vanschelven** [comment]
this is for version 0.3.1

**Comment by lilspikey** [comment]
Ok - hadn't even begun to look at Django 1.2 so thanks for trying this out.

I imagine there may be a few more of these in there, as had to use a few internal bits in Django to get it working...

**Comment by johnsensible** [comment]
Version 0.3.2 should now work in Django 1.2 (and should be backwards compatible with Django 1.1 still).
